### ISSUE TITLE
In hi.serlo.org english navigation is shown

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#609] opened 2020-10-18 18:17 UTC
The navigation is implemented in the backend, shown in the old design, but in the new one the english-navigation is presented to the user.

**Comment by kulla** [comment] 2020-10-19 13:29
This seems to be a duplicate of https://github.com/serlo/api.serlo.org/issues/76 There is a fix for it, however it is not deployed in production yet.

Have you fixed https://serlo.slack.com/archives/C94A2UXN1/p1598875428001600 in the meanwhile? Afterwards you should see the Hindi navigation in the frontend.

**Comment by jakobwes** [comment] 2020-10-19 19:02
I can't log in via browser into the slack-workspace at the moment (for whatever reasons and it won't let me reset my password). But if you mean the problems that there are no uris: this is fixed since a bit. Could then be a similar problem of like #608

**Closed as completed** 2020-11-10 12:23 UTC
Labels: bug
