### ISSUE TITLE
Show Comments without login in staging

### ISSUE THREAD

**Issue by elbotho** [serlo/frontend#1016] opened 2021-05-12 15:24 UTC
Currently comments are hidden for non authed users.

**Comment by Entkenntnis** [comment] 2021-05-12 20:08
Any ideas why this is happening on staging? Can't reproduce in production and locally --- 

Note: Ok, it looks like the guard is blocking the comment form: renderContent is within a guard. Is this intended this way?

**Comment by elbotho** [comment] 2021-05-12 21:55
See https://github.com/serlo/frontend/commit/697f9ba545a8fd492d6b4d38a72df53257ecaa34#r50743066

**Comment by Entkenntnis** [comment] 2021-05-13 07:24
Fixed with 2a1d071f6cca18e2b9123f5bb5b3fb12e2fab4c6 - alright, I have probably forgot to delete something after a test ^^

**Closed as completed by Entkenntnis** 2021-05-13 07:24 UTC
Labels: bug

**Comment by elbotho** [comment] 2021-05-13 08:37
Seems to be working again, thanks!
