### ISSUE TITLE
Secondary menu: Arrows to small

### ISSUE THREAD

**Issue by kulla** [serlo/frontend#59] opened 2020-04-05 19:41 UTC
In the last Lama-meeting I got the feedback that the arrows in the secondary menu are to small in order to comfortably click on them on a mobile phone:

![2020-04-05-213906_659x525_scrot](https://user-images.githubusercontent.com/1327215/78508316-3236da00-7786-11ea-9f16-ad1bfd1b150a.png)

**Comment by Entkenntnis** [comment] 2020-04-06 06:20
Did someone try to actually scroll the whole menu? The arrrows should be a hint that this is possible. Probably not that obvious ...

**Comment by kulla** [comment] 2020-04-06 10:41
I got this hint by Jakob, maybe you can ask him -> I guess, it is not clear enough that the arrows are actually hints...

**Comment by jakobwes** [comment] 2020-04-06 13:24
I tried. It feels like you are supposed to click on the arrows to scroll through the menu, but they are too small to do this comfortably. I would switch to another visualization, if they are more meant as hints to scroll (maybe some sort of scrollbar), or make them bigger to comfortably click through the menu (like in a classical scroll-gallery)

**Comment by elbotho** [comment] 2020-04-09 08:44
Being an expert on this (after about 10 UX blogs on horizontal scrolling ;) I come to the conclusion that almost nobody uses arrows/offers an clickable interface at all.
On touch devices it's seems to be enough to make sure there is always a part of the next item visible (works better if they have a box / background).
To help some add starting animations or a "see all" link next to it.

This currently only affects the "about serlo" section so I'm actually okay with people on mobile maybe not finding all the information. But we might also add it to the community-area later.

**Comment by Entkenntnis** [comment] 2020-04-15 10:04
https://github.com/serlo/frontend/blob/c97700ff64c996a771764fe1cd11d95d05305645/src/components/navigation/MobileMetaMenu.tsx

**Comment by elbotho** [comment] 2020-04-18 08:39
@jakobwes could you try the new custom search: https://frontend.dal123.now.sh/ on mobile and tell me how the refinements filter (Alle Artikel, Videos …) works for you in this regard?
![image](https://user-images.githubusercontent.com/1258870/79632621-cb8bc600-8160-11ea-93a5-bf2d022f5012.png)

Thanks!

**Comment by jakobwes** [comment] 2020-04-18 10:52
@elbotho this works really well for me! In my feeling the options are a bit small compared to the other text (this could also a personal aesthetical thing which shouldn't matter), but it is intuitive that you are supposed to scroll to see the other options. Also I think the underscore helps to understand, that the focused option is one option among others and you can/are supposed to switch it.

**Comment by elbotho** [comment] 2020-05-05 13:52
@jakobwes Want to try this one again? https://frontend-git-mobilemetanav-alternative.serlo.now.sh/serlo

**Comment by jakobwes** [comment] 2020-05-05 15:27
I really like it, especially on mobile where the scroll bar then disappears :)

Maybe just one point. On small desktops I feel the always visible scrollbar puts a lot of focus on the menu (the scrollbar does not fit perfectly to the other design elements I feel, because it is the only place where you see this tone of grey and the grey has more "energy" than most of the other colors). So one idea could be (if possible) to style the scrollbar also in serlo-blue or make it disappear like on mobile. But this is not that important and nevertheless I really like the design/it feels extremely intuitive that you are supposed to scroll through this, if you want to see more pages!

**Comment by elbotho** [comment] 2020-05-06 16:48
@jakobwes Thanks for your thorough feedback again. 
The small desktop problem is actually what led to the first iteration with clickable arrows etc. so we will have to make a choice for now and improve on it going forward. I'd go with the best mobile experience for now. 
@Entkenntnis what do you think?
@simonkoehl want wo check out the meta-nav on iOS https://frontend-git-mobilemetanav-alternative.serlo.now.sh/serlo in comparison to the current one?

**Comment by Entkenntnis** [comment] 2020-05-06 18:41
I tried the new design on firefox mobile and it works quite well except page width:

![Screenshot_2020-05-06-20-39-54](https://user-images.githubusercontent.com/13507950/81215635-eb810d80-8fd9-11ea-9ef2-c8e3177f47cb.png)

**Comment by simonkoehl** [comment] 2020-05-06 18:54
It works quite well on iOS. How about getting rid of the frame:

![Neue Sub-Navi](https://user-images.githubusercontent.com/3379377/81216810-d1e0c580-8fdb-11ea-8658-5e19114097b9.png)

**Comment by elbotho** [comment] 2020-05-06 20:06
@Entkenntnis oh no it's back again :) I'm afraid it's unrelated, but actually caused by the horizon ie11 fix. 
will add a commit to solve this.

@simonkoehl Look better no question, but I'd go with the more obvious solution for now.

**For small desktops**: any great ideas? I consider a fallback, basically an unfolded no scroll version for non-touch devices (probably not super pretty but usable) or a version that styles/hides the scrollbar in a smart way.

**Comment by simonkoehl** [comment] 2020-05-06 20:37
@elbotho are you sure it is more obvious with the frame? My first intuition with the frame was "button". The fade out effect at the right hand side is the only thing that indicates the slider. And this effect is weaker with the frame imo. But I can do some testing with 3-5 people here in the house to disprove that, if you provide me with a link?

**Comment by elbotho** [comment] 2020-05-07 08:59
Okay, sind the feedback was rather positive, I merged this into the current metamenu, since there is not much difference between markup/logic now. this way we save code and markup.
I also did some changes to the layout so we can display the full menu starting from the `md` breakpoint (at 1024) which should work for most small desktops. 
@Entkenntnis would you review this for me? 
https://github.com/serlo/frontend/pull/158

**Comment by elbotho** [comment] 2020-05-07 09:03
@simonkoehl I moved your suggestion to a new issue #169 and will address after https://github.com/serlo/frontend/milestone/1

**Comment by simonkoehl** [comment] 2020-05-07 09:04
perfect, thanks!

**Closed** 2020-05-07 18:53 UTC
Labels: enhancement
