### ISSUE TITLE
Authentication: Improve sign up flow

### ISSUE THREAD

**Issue by CodingDive** [serlo/frontend#2190] opened 2023-03-08 17:41 UTC
I just created a new account and as I clicked on the email confirmation email, the tab in which I signed up to Serlo still looks like the following

url: https://de.serlo.org/auth/registration
![image](https://user-images.githubusercontent.com/28842311/223788231-19aff64d-597d-4264-81e8-19bed13f595b.png)

We should be using the `BroadcastChannel` after clicking the verification link to make the signup flow nicer and communicate with the open tab that the email has been verified. This would also allow us to automatically log in the user instead of having `signup => email verification => signin => logged in`, the new flow could just be `signup => email verification => logged in`.

**Comment by Entkenntnis** [comment] 2023-03-08 17:52
Hi Mikey, thank you for your initiative here.

Feature request like this have to go through the "Feature-Entwicklungsprozess", because we have a lot of things in the backlog and need to prioritize them - you can add your idea as a concept there.

As far as I see, the behaviour is not a bug or broken, therefore I'm closing this issue.

**Closed as not planned by Entkenntnis** 2023-03-08 17:52 UTC
Labels: feedback

**Comment by elbotho** [comment] 2023-03-08 17:57
(ping @hugotiburtino)

**Comment by hugotiburtino** [comment] 2023-03-09 14:48
Hey @CodingDive 
Thanks for your suggestion. I'd also like to improve many things regarding user management but I couldn't to agree more with Entkenntnis. 
As I can see, you have 2 suggestions, the first is to synchronize tabs. It could be a mini-feature and a good chance for your Einarbeitung (I can't find a good word in English for such meaning) 😉. The second is to log in a user after verification. Our user management depends heavily on Ory Kratos and as far as can see it is not supported ([session can be used only in registration flow](https://www.ory.sh/docs/kratos/hooks/configure-hooks#webhooks)). I'll open an feat request in https://github.com/ory/kratos for extending the session action to other flows, if you don't it first.

**Comment by hugotiburtino** [comment] 2023-03-11 12:00
See https://github.com/ory/kratos/issues/3160

**Comment by CodingDive** [comment] 2023-03-11 12:30
Thanks @hugotiburtino for raising the issue in `kratos`. I'll add my feature request to our backlog 👍
