### ISSUE TITLE
Normalize styling of interest dropdown for firefox  inLinux and windows 

### ISSUE THREAD

**Issue by hugotiburtino** [serlo/frontend#2134] opened 2023-02-23 13:03 UTC
From the Beta-testing-Document

![image](https://user-images.githubusercontent.com/45924645/220914142-1e742038-905f-40d9-8a8b-e12216632820.png)

![image](https://user-images.githubusercontent.com/45924645/220914268-262c3d5a-9c33-48c8-bff0-ec3d18c80e40.png)

(to be honest, given the low number of linux users, it can be left like that if it is too complicated. But the windows problem poses also are a11y issue)

**Comment by elbotho** [comment] 2023-02-23 13:25
yeah, I purposely only styled the selection box itself consistently across browsers. The dropdown is left mostly unchanged.
The alternative would be to completely replace the native elements with js-powered components.
And I agree the windows version is not as intended :)

**Comment by elbotho** [comment] 2023-02-27 12:50
closed by 19d11a0c535145008c69f379dc2783ba869cb9a1

**Closed as completed by elbotho** 2023-02-27 12:50 UTC
Labels: feedback
