### ISSUE TITLE
When clicking on profile-links on the /team-page I get an error

### ISSUE THREAD

**Issue by jakobwes** [serlo/frontend#898] opened 2021-02-16 10:30 UTC
On here https://de.serlo.org/team I get an error "This page (https://de.serlo.org/de/user/profile/Adrian_B) is currently offline. However, because the site uses Cloudflare's Always Online™ technology you can continue to surf a snapshot of the site." and get rerouted to the old frontend. If I click on "Retry for a live version" then it works, but I only get the old frontend.

**Comment by inyono** [comment] 2021-02-16 11:44
Either frontend or Cloudflare Worker issue. The`de/` part is definitely wrong.

**Comment by Entkenntnis** [comment] 2021-02-16 14:47
This is the reproducable edge case we have been searching for 👍

**Comment by inyono** [comment] 2021-02-16 17:14
Some findings:
- API seems to work correctly, see e.g.
```graphql
{
  uuid(alias: { instance: de, path: "/user/profile/admin" }) {
    __typename
    ... on User {
      alias
    }
  }
}

```
on staging

- Cloudflare Worker also seems to handle that URL correctly

So most likely a bug in `pages/user/[...userslug.tsx]` (which doesn't use the alias, for example. Locally, even `/user/profile/:id` doesn't work as expected).

**Comment by elbotho** [comment] 2021-02-19 10:56
`/user/profile/:id` is not supported by the frontend. Currently we only support the new aliases:
e.g. `/user/10/simon` or `/user/10`.

`user/profile/…` links are redirected to legacy frontend by our `<Link>` component (expected behaviour).
The redirect to `de/user/profile…` is maybe a [CF-Worker bug](https://github.com/serlo/serlo.org-cloudflare-worker/issues/153).


### Options

- use new aliases in content
- use new aliases in content and add test link in sandbox so @kulla can use this to investigate https://github.com/serlo/serlo.org-cloudflare-worker/issues/153
- add support for `/user/profile/{name}` to frontend


Opinions? @Entkenntnis @inyono @kulla

**Comment by inyono** [comment] 2021-02-19 11:25
The redirect looks correctly from Cloudflare Worker:
```
$ curl -v https://de.serlo.org/user/profile/inyono
< HTTP/2 301
< location: https://de.serlo.org/user/15473/inyono
```
You even have the `de` behavior on frontend.serlo.org, which works w/o CF Worker, see https://frontend.serlo.org/team. So might be a bug in the Link component.

Independent from that: we can probably just query by alias in `pages/user/[...userslug].tsx` so that frontend isn't depending on the actual way we do canonical aliases for user at the moment. Most likely won't fix this specific issue but makes `pages/user/[...userslug].tsx` more resilient / future-proof.

**Comment by kulla** [comment] 2021-02-22 13:17
When you click on a link at `/team` you see for short time the page loading animation of the frontend. Afterwards a link like https://de.serlo.org/de/user/profile/anbestCL with an additional `de` is loaded instead of https://de.serlo.org/user/profile/anbestCL Since CF cannot get the current alias of `/de/user/profile/anbestCL` it sends the request to the legacy backend which can resolve the link (I do not know how :see_no_evil: ).

**Comment by kulla** [comment] 2021-02-22 13:27
> `user/profile/…` links are redirected to legacy frontend by our `<Link>` component (expected behaviour).

How about deleting https://github.com/serlo/frontend/blob/staging/src/components/content/link.tsx#L36 so that `/user/profile/` is not handled client side?!

**Comment by Entkenntnis** [comment] 2021-02-24 08:19
I will look at it the next days (still quite busy right now)

Edit: #912 could be a possible fix for this.

**Closed as completed** 2021-02-25 12:37 UTC
