### ISSUE TITLE
Navigating back / forward doesn't work sometimes

### ISSUE THREAD

**Issue by inyono** [serlo/frontend#519] opened 2020-08-27 04:42 UTC
To reproduce:
- Enable frontend
- Open a new tab with https://de.serlo.org
- Navigate to https://de.serlo.org/mathe
- Use the browser's back button to navigate back to / (an unexpected error occurs)
- Use the browser's forward button to navigate back to /mathe (another unexpected error occurs)

**Comment by elbotho** [comment] 2020-08-27 06:29
Can't reproduce on localhost, but occurs on staging.

First error on back:
```TypeError: n.join is not a function at get-initial-props.ts:21 …```

Second error on forward:
```TypeError: Cannot read property 'lang' of undefined at jt ([[...slug]].tsx:88) …```

**Comment by elbotho** [comment] 2020-08-27 06:33
Also works fine on [branch previews](https://frontend-git-less-license-notices.serlo.vercel.app/) so it might be related to cf-worker, but I don't really see how. needs more 🔍 .

**Comment by Entkenntnis** [comment] 2020-08-28 12:09
Can reproduce, will investigate this.

**Comment by Entkenntnis** [comment] 2020-08-28 13:43
The problem was, that a slug with a single entry is passed as string (and not string[]), and that causes the join function to fail.

Fixed by 0e38759a9c4cdfe51e1a2e326922770240219d7a

**Comment by Entkenntnis** [comment] 2020-08-28 13:53
There is still another problem with this...

**Comment by Entkenntnis** [comment] 2020-08-28 14:03
Should be fixed by 59399ece99f24866860f00e450025f16a70a00c5 now.

**Closed as completed by Entkenntnis** 2020-08-28 14:03 UTC
Labels: bug
