### ISSUE TITLE
e2e testing (plugin-toolbar): I need to click "Füge ein Element hinzu" twice

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#2645] opened 2023-07-24 22:16 UTC
link: https://frontend-git-feat-plugin-toolbar-serlo.vercel.app/entity/create/Article/1337

![grafik](https://github.com/serlo/frontend/assets/13507950/93de51d3-b5a2-4d06-afad-03cd4533b823)

Initial focus is in image caption.

Expected behaviour:

- Clicking "Füge ein Element hinzu" opens plugin suggestions

Actual behaviour:

- Clicking "Füge ein Element hinzu" unfocus the image caption
- I need to click again to get suggestions

**Comment by hejtful** [comment] 2023-07-25 07:55
This was caused by layout shifting (mousedown outside of image plugin -> image plugin unfocus -> caption hidden -> new plugin button shifts up for the height of the caption -> mouseclick misses the button).

Fixed by always showing the caption field, even if it's empty and the image plugin is not focused ([commit link](https://github.com/serlo/frontend/pull/2571/commits/de9092a65c682afcbe134bb15b31bcdeabe1d3d4)).

@elbotho It seemed like the simplest solution to unblock the tests. If you have an idea how to do it better, I'd be happy to implement it.

@Entkenntnis Could you please run the tests again to check if it works, or maybe explain to me how to run the tests for a specific branch?

**Comment by Entkenntnis** [comment] 2023-07-25 08:17
@hejtful Here is a quick overview how to run tests locally:

- Create production build and start it (`yarn build && yarn start`
- clone https://github.com/serlo/frontend-e2e-tests
- enter directory and run `yarn`
- uncomment line 4 in https://github.com/serlo/frontend-e2e-tests/blob/main/.env 
- `yarn test tests/400-serlo-editor.ts` for editor tests

**Comment by hejtful** [comment] 2023-07-25 08:55
Thank you! Works like a charm. After the fix, 15 tests are passing and 3 are failing, so I'd say this issue is fixed, so I'll close it. Maybe we decide for a more visually pleasing fix in the future, but for now the tests are unblocked.

**Closed as completed by hejtful** 2023-07-25 08:55 UTC
