### ISSUE TITLE
pdf download redirect is not working

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/frontend#1284] opened 2021-09-17 08:21 UTC
https://de.serlo.org/api/pdf/2055 is not working atm. The pdf export itself is up and running: https://pdf.serlo.org/api/2055

Maybe support in cf worker is missing? or there is a problem with rewrite.

**Comment by elbotho** [comment] 2021-09-17 10:36
Works for me if I use the dialog. Can you reproduce?

**Comment by Entkenntnis** [comment] 2021-09-18 09:09
It's working for me on localhost, but not in production. I've waited about a minute, but it was still not showing the file.

**Comment by elbotho** [comment] 2021-09-18 20:52
does this work for example (again using the dialog and just pressing the button w/ left mouse)?
https://de.serlo.org/mathe/1565/sinus-kosinus-und-tangens

any console output?
what is the network response?

**Comment by Entkenntnis** [comment] 2021-09-19 06:34
there is no console output, and no network response - but I see a request to https://de.serlo.org/api/pdf/1565 that is stuck forever.

Can you test https://de.serlo.org/api/pdf/1565 directly? Is this working for you? For me, it's just

![grafik](https://user-images.githubusercontent.com/13507950/133917962-9377c61c-6a8b-4e66-bf63-61a19982b986.png)

**Comment by elbotho** [comment] 2021-09-19 08:18
yeah, direct access does not work because it's not redirected via nextjs and we need to add it to cf-worker (or fall back to the subdomain version).
But inside nextjs it works flawlessly for me so that's why i'm confused.

After some testing it seems to be a firefox/chrome thing.

cf issue:
https://github.com/serlo/serlo.org-cloudflare-worker/issues/234

**Comment by Entkenntnis** [comment] 2021-09-22 07:50
Because cf approach is moving on, 42fd91688c8fe7243626d63c3fc7322373440a95 reverts rewrites and adds a fix for localhost (reason: #1268)

**Comment by hxwalther** [comment] 2021-09-23 15:49
I checked :   https://de.serlo.org/mathe/1565/sinus-kosinus-und-tangens
(Now) It's working for me too  ... 
I'll check other Articles , ThaXXX for fix this issue  ....

**Comment by elbotho** [comment] 2021-09-23 15:53
@hxwalther thanks for the feedback, 
currently trying to improve it even further so the files get a nice name again.

**Comment by elbotho** [comment] 2021-09-27 09:28
now fixed with cf-worker proxy. working as intended again.

**Closed as completed** 2021-09-27 09:29 UTC
Labels: bug
